# Specify the docker image to use
image: ubuntu:14.04

# Define the commmands that run before each job's script
before_script:
  - apt-get update
  - curl -sL https://deb.nodesource.com/setup_11.x | -E bash -
  - apt-get install -y nodejs
production:
  script:
    - npm run prod
