const getCuratedValue = (rawInput) => {
  const list = {
    user_age_14_to_18: '14 to 18',
    user_age_19_to_23: '19 to 23',
    user_age_24_to_30: '24 to 30',
    user_age_31_to_40: '31 to 40',
    user_age_41_to_50: '41 to 51',
    user_age_51_or_more: '51 or more',
    us_accent_opt: 'us',
    uk_accent_opt: 'uk',
    pd_beginner_level: 'beginner',
    pd_intermediate_level: 'intermediate',
    pd_advanced_level: 'advanced',
    option1_not_important: '1',
    option2_slightly_important: '2',
    option3_important: '3',
    option4_very_important: '4',
    option5_extremely_important: '5',
    english_is_boring_option: 'english is boring',
    dont_have_motivation_option: 'lack of motivation',
    dont_have_time_option: 'lack of time',
    bad_teacher_option: 'bad teachers',
    learning_english_most_important_option: 'learning english',
    practicing_english_most_important_option: 'practicing english',
    getting_corrected_most_important_option: 'getting corrected',
    learning_english_vocabulary_important: 'vocabulary',
    learning_english_conversation_important: 'conversation',
    learning_english_grammar_important: 'grammar',
    learning_english_listening_important: 'listening',
    dont_like_idea_of_learning_with_friend: 'no',
    unsure_of_idea_of_learning_with_friend: 'not sure',
    maybe_like_idea_of_learning_with_friend: 'maybe',
    yes_like_idea_of_learning_with_friend: 'yes',
    definitely_like_idea_of_learning_with_friend: 'definitely',
    dont_like_idea_of_bot_correcting_me: 'no',
    unsure_like_idea_of_bot_correcting_me: 'not sure',
    maybe_like_idea_of_bot_correcting_me: 'maybe',
    yes_like_idea_of_bot_correcting_me: 'yes',
    definitely_like_idea_of_bot_correcting_me: 'definitely',
    no_dont_want_to_be_part_of_community: 'no',
    maybe_make_me_part_of_community: 'maybe',
    yes_make_me_part_of_community: 'yes',
    yes_join_country_community: 'yes',
    no_dont_join_country_community: 'no',
  };
  return list[rawInput];
};

module.exports = getCuratedValue;
